vars:
  - clean_path: data/clean
  - ml_ready_path: data/ml_ready
  - ml_results_path: data/ml_results
  - viz_path: data/viz
  - model_type: "gevd_stationary_iid"
  - covariate: "gmst"
  - dataset: "aemet"
  # MCMC PARAMETERS
  - num_mcmc_samples: 1_000
  - num_mcmc_chains: 4
  - num_mcmc_warmup: 1_000
  - num_map_warmup: 30_000
  # VIZ PARAMS
  - station_id: "8414A"
  - t2m_station_ids:
      - "8414A"
      - "3129A"
  - pr_station_ids:
      - "8414A"
stages:
  # EXPERIMENT - 2M MAX TEMPERATURE
  # I - Train MCMC Model
  aemet_t2m_stations_spain_mcmc_train:
    wdir: ./../../../../
    cmd: >-
      python st_evt/_src/modules/models/${dataset}/gevd_stationary_iid/model.py train-model-gevd-mcmc
      --dataset-path '${ml_ready_path}/${dataset}/t2max_stations_bm_summer.zarr'
      --save-path '${ml_results_path}/${dataset}/t2max/spain/${model_type}/mcmc/'
      --variable 't2max'
      --covariate '${covariate}'
      --num-mcmc-samples '${num_mcmc_samples}'
      --num-chains '${num_mcmc_chains}'
      --num-mcmc-warmup '${num_mcmc_warmup}'
      --num-map-warmup '${num_map_warmup}'
    deps:
    - st_evt/_src/modules/models/aemet/gevd_stationary_iid/model.py
    - ${ml_ready_path}/aemet/t2max_stations_bm_summer.zarr
    outs:
    - ${ml_results_path}/${dataset}/t2max/spain/${model_type}/mcmc/az_nonstationary.zarr
    - ${ml_results_path}/${dataset}/t2max/spain/${model_type}/mcmc/az_posterior_params.yaml
  # II - EVALUATE MODEL - STATION
  aemet_t2m_stations_spain_mcmc_evaluate_station:
    foreach: ${t2m_station_ids}
    do:
      wdir: ./../../../../
      cmd: >-
        python st_evt/_src/modules/models/${dataset}/gevd_stationary_iid/post_analysis.py evaluate-model-gevd-mcmc-station
        --dataset-path '${ml_results_path}/${dataset}/t2max/spain/${model_type}/mcmc/az_nonstationary.zarr'
        --save-path '${viz_path}/${dataset}/t2max/${item}/${model_type}/mcmc/'
        --variable 't2max'
        --covariate '${covariate}'
        --station-id "${item}"
      deps:
      - st_evt/_src/modules/models/aemet/gevd_stationary_iid/post_analysis.py
      - ${ml_results_path}/${dataset}/t2max/spain/${model_type}/mcmc/az_nonstationary.zarr
      outs:
      - ${viz_path}/${dataset}/t2max/${item}/${model_type}/mcmc/params/trace.png
      - ${viz_path}/${dataset}/t2max/${item}/${model_type}/mcmc/params/joint.png
      - ${viz_path}/${dataset}/t2max/${item}/${model_type}/mcmc/metrics/qq_plot.png
      - ${viz_path}/${dataset}/t2max/${item}/${model_type}/mcmc/metrics/rmse_density.png
      - ${viz_path}/${dataset}/t2max/${item}/${model_type}/mcmc/metrics/mae_density.png
      - ${viz_path}/${dataset}/t2max/${item}/${model_type}/mcmc/returns/rp_vs_obs.png
      - ${viz_path}/${dataset}/t2max/${item}/${model_type}/mcmc/returns/rl100_density.png
  # III - EVALUATE MODEL - STATION
  aemet_t2m_stations_spain_mcmc_evaluate_region:
    wdir: ./../../../../
    cmd: >-
      python st_evt/_src/modules/models/${dataset}/gevd_stationary_iid/post_analysis.py evaluate-model-gevd-mcmc-spain
      --dataset-path '${ml_results_path}/${dataset}/t2max/spain/${model_type}/mcmc/az_nonstationary.zarr'
      --save-path '${viz_path}/${dataset}/t2max/spain/${model_type}/mcmc/'
      --variable 't2max'
      --covariate '${covariate}'
    deps:
    - st_evt/_src/modules/models/aemet/gevd_stationary_iid/post_analysis.py
    - ${ml_results_path}/${dataset}/t2max/spain/${model_type}/mcmc/az_nonstationary.zarr
    outs:
    - ${viz_path}/${dataset}/t2max/spain/${model_type}/mcmc/nll/nll_density.png
    - ${viz_path}/${dataset}/t2max/spain/${model_type}/mcmc/nll/nll_map.png
    - ${viz_path}/${dataset}/t2max/spain/${model_type}/mcmc/nll/nll_covariates_lon.png
    - ${viz_path}/${dataset}/t2max/spain/${model_type}/mcmc/nll/nll_covariates_lat.png
    - ${viz_path}/${dataset}/t2max/spain/${model_type}/mcmc/nll/nll_covariates_alt.png
  # EXPERIMENT - PRECIPITATION
  # I - Train MCMC Model
  aemet_pr_stations_spain_mcmc_train:
    wdir: ./../../../../
    cmd: >-
      python st_evt/_src/modules/models/${dataset}/gevd_stationary_iid/model.py train-model-gevd-mcmc
      --dataset-path '${ml_ready_path}/${dataset}/pr_stations_bm_fall.zarr'
      --save-path '${ml_results_path}/${dataset}/pr/spain/${model_type}/mcmc/'
      --variable 'pr'
      --covariate '${covariate}'
      --num-mcmc-samples '${num_mcmc_samples}'
      --num-chains '${num_mcmc_chains}'
      --num-mcmc-warmup '${num_mcmc_warmup}'
      --num-map-warmup '${num_map_warmup}'
    deps:
    - st_evt/_src/modules/models/aemet/gevd_stationary_iid/model.py
    - ${ml_ready_path}/aemet/pr_stations_bm_fall.zarr
    outs:
    - ${ml_results_path}/${dataset}/pr/spain/${model_type}/mcmc/az_nonstationary.zarr
    - ${ml_results_path}/${dataset}/pr/spain/${model_type}/mcmc/az_posterior_params.yaml
  # II - EVALUATE MODEL - STATION
  aemet_pr_stations_spain_mcmc_evaluate_station:
    foreach: ${pr_station_ids}
    do:
      wdir: ./../../../../
      cmd: >-
        python st_evt/_src/modules/models/${dataset}/gevd_stationary_iid/post_analysis.py evaluate-model-gevd-mcmc-station
        --dataset-path '${ml_results_path}/${dataset}/pr/spain/${model_type}/mcmc/az_nonstationary.zarr'
        --save-path '${viz_path}/${dataset}/pr/${item}/${model_type}/mcmc/'
        --variable 'pr'
        --covariate '${covariate}'
        --station-id "${item}"
      deps:
      - st_evt/_src/modules/models/aemet/gevd_stationary_iid/post_analysis.py
      - ${ml_results_path}/${dataset}/pr/spain/${model_type}/mcmc/az_nonstationary.zarr
      outs:
      - ${viz_path}/${dataset}/pr/${item}/${model_type}/mcmc/params/trace.png
      - ${viz_path}/${dataset}/pr/${item}/${model_type}/mcmc/params/joint.png
      - ${viz_path}/${dataset}/pr/${item}/${model_type}/mcmc/metrics/qq_plot.png
      - ${viz_path}/${dataset}/pr/${item}/${model_type}/mcmc/metrics/rmse_density.png
      - ${viz_path}/${dataset}/pr/${item}/${model_type}/mcmc/metrics/mae_density.png
      - ${viz_path}/${dataset}/pr/${item}/${model_type}/mcmc/returns/rp_vs_obs.png
      - ${viz_path}/${dataset}/pr/${item}/${model_type}/mcmc/returns/rl100_density.png
  # III - EVALUATE MODEL - STATION
  aemet_pr_stations_spain_mcmc_evaluate_region:
    wdir: ./../../../../
    cmd: >-
      python st_evt/_src/modules/models/${dataset}/gevd_stationary_iid/post_analysis.py evaluate-model-gevd-mcmc-spain
      --dataset-path '${ml_results_path}/${dataset}/pr/spain/${model_type}/mcmc/az_nonstationary.zarr'
      --save-path '${viz_path}/${dataset}/pr/spain/${model_type}/mcmc/'
      --variable 'pr'
      --covariate '${covariate}'
    deps:
    - st_evt/_src/modules/models/aemet/gevd_stationary_iid/post_analysis.py
    - ${ml_results_path}/${dataset}/pr/spain/${model_type}/mcmc/az_nonstationary.zarr
    outs:
    - ${viz_path}/${dataset}/pr/spain/${model_type}/mcmc/nll/nll_density.png
    - ${viz_path}/${dataset}/pr/spain/${model_type}/mcmc/nll/nll_map.png
    - ${viz_path}/${dataset}/pr/spain/${model_type}/mcmc/nll/nll_covariates_lon.png
    - ${viz_path}/${dataset}/pr/spain/${model_type}/mcmc/nll/nll_covariates_lat.png
    - ${viz_path}/${dataset}/pr/spain/${model_type}/mcmc/nll/nll_covariates_alt.png