vars:
  - clean_path: data/clean
  - ml_ready_path: data/ml_ready
  - ml_results_path: data/ml_results
  - model_type: "gevd_stationary_iid"
  - variable: "t2max_bm_year"
  - covariate: "gmst"
stages:
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  aemet_stations_mcmc_train:
    wdir: ./../../../../
    cmd: >-
      python st_evt/_src/modules/models/aemet/st_gevd_stationary_iid.py train-model-gevd-mcmc
      --dataset-path '${ml_ready_path}/aemet/t2max_stations_bm_summer.zarr'
      --save-path '${ml_results_path}/aemet/t2max/${model_type}/mcmc/'
      --variable '${variable}'
      --covariate '${covariate}'
      --num-mcmc-samples 10
      --num-chains 1
      --num-mcmc-warmup 10
      --num-map-warmup 10
    deps:
    - st_evt/_src/modules/models/aemet/st_gevd_stationary_iid.py
    - ${ml_ready_path}/aemet/t2max_stations_bm_summer.zarr
    outs:
    - ${ml_results_path}/aemet/t2max/${model_type}/mcmc/az_nonstationary.zarr
    - ${ml_results_path}/aemet/t2max/${model_type}/mcmc/az_posterior_params.yaml
  # # DO OTHER STUFF
  # aemet_stations_mcmc_evaluate:
  #   foreach: ${eda.station_ids}
  #   do:
  #     wdir: ./../../../
  #     cmd: >-
  #       python st_evt/_src/modules/models/ts_nonstationary/aemet.py evaluate-model-station
  #       --load-path '${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}'
  #       --save-path '${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}/figures'
  #     params:
  #       - pipelines/models/timeseries/params.yaml:
  #         - model.model_type
  #     deps:
  #     - st_evt/_src/modules/models/ts_nonstationary/aemet.py
  #     outs:
  #     - ${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}/figures/trace.png
  #     - ${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}/figures/params_joint.png
