filepaths:
  ml_ready_path: ../../../data/ml_ready
  ml_results_path: ../../../data/ml_results
eda:
  station_ids:
    - "8414A"
    - "3129A"
    - "9434"
    - "1475X"
model:
  model_type: linear
  seed: 123
  num_chains: 4
  num_mcmc_samples: 1_000
