# TODO: Download E-OBS Data - 2m Max Temperature
# TODO: Download E-OBS Data - Precipitation
# TODO: Download E-OBS Data - Wind Speed
stages:
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  download_aemet:
   cmd: python ../../st_evt/_src/modules/download/aemet.py --filepath '${filepaths.raw_path}'
   params:
     - filepaths.raw_path
   deps:
    - ../../st_evt/_src/modules/download/aemet.py
   outs:
     - ../../data/raw/tmax_homo.csv
     - ../../data/raw/pr.csv
     - ../../data/raw/spain_stations.csv
     - ../../data/raw/red_feten.csv
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  download_gmst:
   cmd: python ../../st_evt/_src/modules/download/gmst.py --filepath '${filepaths.raw_path}'
   params:
     - filepaths.raw_path
   deps:
    - ../../st_evt/_src/modules/download/gmst.py
   outs:
     - ../../data/raw/gmst_david.xlsx
