# TODO: Download E-OBS Data - 2m Max Temperature
# TODO: Download E-OBS Data - Precipitation
# TODO: Download E-OBS Data - Wind Speed
stages:
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  download_aemet:
    desc: Download AEMET station data from google drive.
    wdir: ./../../
    cmd: python st_evt/_src/modules/download/aemet.py --filepath '${filepaths.raw_path}/aemet'
    params:
     - filepaths.raw_path
    deps:
     - st_evt/_src/modules/download/aemet.py
    outs:
     - data/raw/aemet/tmax_homo.csv
     - data/raw/aemet/pr.csv
     - data/raw/aemet/spain_stations.csv
     - data/raw/aemet/red_feten.csv
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  download_gmst:
    wdir: ./../../
    cmd: python st_evt/_src/modules/download/gmst.py --filepath '${filepaths.raw_path}/gmst'
    params:
     - filepaths.raw_path
    deps:
     - st_evt/_src/modules/download/gmst.py
    outs:
     - data/raw/gmst/gmst_david.xlsx
