# TODO: Download E-OBS Data - 2m Max Temperature
# TODO: Download E-OBS Data - Precipitation
# TODO: Download E-OBS Data - Wind Speed
vars:
  - raw_path: data/raw
  - clean_path: data/clean
  - ml_ready_path: data/ml_ready
stages:
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  download_aemet:
    desc: Download AEMET station data from google drive.
    wdir: ./../../
    cmd: python st_evt/_src/modules/download/aemet.py --filepath '${raw_path}/aemet'
    deps:
     - st_evt/_src/modules/download/aemet.py
    outs:
     - ${raw_path}/aemet/tmax_homo.csv
     - ${raw_path}/aemet/pr.csv
     - ${raw_path}/aemet/spain_stations.csv
     - ${raw_path}/aemet/red_feten.csv
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  download_gmst:
    wdir: ./../../
    cmd: python st_evt/_src/modules/download/gmst.py --filepath '${raw_path}/gmst'
    deps:
     - st_evt/_src/modules/download/gmst.py
    outs:
     - ${raw_path}/gmst/gmst_david.xlsx
