vars:
  - raw_path: data/raw
  - clean_path: data/clean
  - ml_ready_path: data/ml_ready
  - viz_path: data/viz
  - dataset: aemet
stages:
  # CLEAN AEMET STATION DATA - 2m Max Temperature
  clean_aemet_t2max:
    wdir: ./../../
    cmd: python st_evt/_src/modules/clean/aemet.py clean-t2m-stations --load-path '${raw_path}/aemet' --save-path '${clean_path}/aemet'
    deps:
     - ${raw_path}/aemet/tmax_homo.csv
     - ${raw_path}/aemet/spain_stations.csv
     - ${raw_path}/aemet/red_feten.csv
    outs:
     - data/clean/aemet/t2max_stations.zarr
  # CLEAN AEMET STATION DATA - Precipitation
  clean_aemet_pr:
    wdir: ./../../
    cmd: python st_evt/_src/modules/clean/aemet.py clean-pr-stations --load-path '${raw_path}/aemet' --save-path '${clean_path}/aemet'
    deps:
     - ${raw_path}/aemet/pr.csv
     - ${raw_path}/aemet/spain_stations.csv
     - ${raw_path}/aemet/red_feten.csv
    outs:
     - data/clean/aemet/pr_stations.zarr
  # CLEAN AEMET STATION DATA - 2m Max Temperature
  clean_gmst_david:
    wdir: ./../../
    cmd: python st_evt/_src/modules/clean/gmst.py clean-gmst-david --load-path '${raw_path}/gmst' --save-path '${clean_path}/gmst'
    deps:
     - ${raw_path}/gmst/gmst_david.xlsx
    outs:
     - ${clean_path}/gmst/gmst_david.zarr
  # CLEAN AEMET STATION DATA - 2m Max Temperature
  clean_eobs_pr:
    wdir: ./../../
    cmd: python st_evt/_src/modules/clean/eobs.py clean-pr-eobs --load-path '${raw_path}/eobs' --save-path '${clean_path}/eobs'
    deps:
     - ${raw_path}/eobs/pr_mean_eobs_0.1.nc
     - ${raw_path}/eobs/elev_eobs_0.1.nc
    outs:
     - data/clean/eobs/pr_eobs_spain.zarr
  clean_eobs_elev:
    wdir: ./../../
    cmd: python st_evt/_src/modules/clean/eobs.py clean-elev-eobs --load-path '${raw_path}/eobs' --save-path '${clean_path}/eobs'
    deps:
     - ${raw_path}/eobs/elev_eobs_0.1.nc
    outs:
     - data/clean/eobs/elev_eobs_spain.zarr
  clean_eobs_t2max:
    wdir: ./../../
    cmd: python st_evt/_src/modules/clean/eobs.py clean-t2max-eobs --load-path '${raw_path}/eobs' --save-path '${clean_path}/eobs'
    deps:
     - ${raw_path}/eobs/tmax_mean_eobs_0.1.nc
     - ${raw_path}/eobs/elev_eobs_0.1.nc
    outs:
     - data/clean/eobs/t2max_eobs_spain.zarr
  clean_eobs_ws:
    wdir: ./../../
    cmd: python st_evt/_src/modules/clean/eobs.py clean-windspeed-eobs --load-path '${raw_path}/eobs' --save-path '${clean_path}/eobs'
    deps:
     - ${raw_path}/eobs/ws_mean_eobs_0.1.nc
     - ${raw_path}/eobs/elev_eobs_0.1.nc
    outs:
     - data/clean/eobs/ws_eobs_spain.zarr