vars:
  - clean_path: data/clean
  - ml_ready_path: data/ml_ready
  - ml_results_path: data/ml_results_path
  - station_ids:
    - "8414A"
    - "3129A"
stages:
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  aemet_stations_mcmc_train:
    foreach: ${eda.station_ids}
    do:
      wdir: ./../../../
      cmd: >-
        python st_evt/_src/modules/models/ts_nonstationary/aemet.py train-model-station
        --load-path '${ml_ready_path}'
        --save-path '${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}'
        --station-id '${item}'
      params:
        - pipelines/models/timeseries/params.yaml:
          - model.model_type
      deps:
      - st_evt/_src/modules/models/ts_nonstationary/aemet.py
      outs:
      - ${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}/az_nonstationary.zarr
      - ${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}/az_posterior_params.json
  # DO OTHER STUFF
  aemet_stations_mcmc_evaluate:
    foreach: ${eda.station_ids}
    do:
      wdir: ./../../../
      cmd: >-
        python st_evt/_src/modules/models/ts_nonstationary/aemet.py evaluate-model-station
        --load-path '${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}'
        --save-path '${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}/figures'
      params:
        - pipelines/models/timeseries/params.yaml:
          - model.model_type
      deps:
      - st_evt/_src/modules/models/ts_nonstationary/aemet.py
      outs:
      - ${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}/figures/trace.png
      - ${ml_results_path}/aemet/${item}/nonstationary/${model.model_type}/figures/params_joint.png
