stages:
  # VIZ - STATION - T2MAX
  viz_station_t2max:
    cmd: |
      python ../../st_evt/_src/modules/eda/aemet_station.py viz-t2max-station --load-path '${filepaths.clean_path}' --save-path '${filepaths.viz_eda_path}' --station-id '${eda.station_id}'
    params:
      - filepaths.clean_path
      - filepaths.viz_eda_path
      - eda.station_id
    deps:
      - ../../st_evt/_src/modules/eda/aemet_station.py
      - ../../data/clean/t2max_stations.zarr
  # VIZ - STATION - PRECIPITATION
  viz_station_pr:
    cmd: |
      python ../../st_evt/_src/modules/eda/aemet_station.py viz-pr-station --load-path '${filepaths.clean_path}' --save-path '${filepaths.viz_eda_path}' --station-id '${eda.station_id}'
    params:
      - filepaths.clean_path
      - filepaths.viz_eda_path
      - eda.station_id
    deps:
      - ../../st_evt/_src/modules/eda/aemet_station.py
      - ../../data/clean/pr_stations.zarr
  # VIZ - STATION - PRECIPITATION
  viz_gmst_david:
    cmd: |
      python ../../st_evt/_src/modules/eda/gmst.py viz-gmst-david --load-path '${filepaths.clean_path}' --save-path '${filepaths.viz_eda_path}'
    params:
      - filepaths.clean_path
      - filepaths.viz_eda_path
    deps:
      - ../../st_evt/_src/modules/eda/gmst.py
      - ../../data/clean/gmst_david.zarr