vars:
  - clean_path: data/clean
  - ml_ready_path: data/ml_ready
stages:
  # DOWNLOAD AEMET STATION DATA FROM GDRIVE
  aemet_bm_summer_extremes:
    wdir: ./../../
    cmd: >-
      python st_evt/_src/modules/extremes/aemet.py aemet-t2m-bm-year
      --data-path '${clean_path}/aemet'
      --cov-path '${clean_path}/gmst'
      --save-path '${ml_ready_path}/aemet'
      --output-name 't2max_stations_bm_summer'
      --months ${months}
    params:
     - pipelines/extremes/params.yaml:
         - months
    deps:
     - st_evt/_src/modules/extremes/aemet.py
     - ${clean_path}/gmst/gmst_david.zarr
     - ${clean_path}/aemet/t2max_stations.zarr
    outs:
     - ${ml_ready_path}/aemet/t2max_stations_bm_summer.zarr
